src/newssite/accs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from accs.views import *
app_name='accs'
urlpatterns = [
    path('sign-up/',signup,name='signup'),
    path('sign-in/',signin,name='signin'),
    path('sign-out/',signout,name='signout'),
    path('create-item/',createitem,name='createitem'),
    path('view-item-<int:item_id>/',viewitem,name='viewitem'), 
    path('change-item-<int:item_id>/',change_item,name='change_item'), 
    path('change-item-<int:item_id>/change-subitem-<int:subitem_id>/',change_subitem,name='change_subitem'),
    path('change-item-<int:item_id>/create-subitem/',create_subitem,name='create_subitem'),
    path('profile/',profile,name='profile'),
    path('publication-<int:item_id>/',publication,name='publication')
]

src/newssite/coreapp/urls.py
from coreapp import views
from django.urls import path,include
app_name='coreapp'
urlpatterns = [
 path('',views.gohome,name='gohome')
     
]

src/newssite/newsapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from newsapp import views


app_name='newsapp'
urlpatterns = [
path('',views.home,name='home'),
  path('item-<int:item_id>/',views.item,name='item'),
  path('open-item-<int:item_id>-in-author-mode/',views.open_item_in_author_mode,name='open_item_in_author_mode',)
     
     
]

src/newssite/newssite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from newsapp import views
from accs.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('news/',include('newsapp.urls')),
    path('accs/',include('accs.urls'))
     
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/newssite/coreapp/models.py
from django.db import models

# Create your models here.

src/newssite/coreapp/views.py
from django.shortcuts import render,redirect

def gohome(request):
    return redirect('newsapp:home')
# Create your views here.

src/newssite/coreapp/templates/coreapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NewsSite</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body >
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <header >

    <nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'newsapp:home' %}">NewsSite</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accs:profile' %}">{{ user.username }}</a>
            </li>
            <form action="{% url 'accs:signout' %}" method="POST">
              <li class="nav-item">
                {% csrf_token %}
                <input class="btn btn-outline-secondary" type="submit" value="выйти">
              </li>
            </form>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accs:signin' %}">войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accs:signup' %}">зарегестрироваться</a>
            </li>
            {% endif %}
            </ul>
            
        </div>
      </div>
    </nav>
  </header>
  {% block content %}

  {% endblock %}

    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top ">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="mb-3 mb-md-0 text-muted">© 2023 NewsSite, Inc</span>
        </div>
    
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
          <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
      </footer>
    </div>

</body>
</html>