src/newssite/accs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from accs.views import *
app_name='accs'
urlpatterns = [
    path('sign-up/',signup,name='signup'),
    path('sign-in/',signin,name='signin'),
    path('sign-out/',signout,name='signout'),
    path('create-item/',createitem,name='createitem'),
    path('view-item-<int:item_id>/',viewitem,name='viewitem'), 
    path('change-item-<int:item_id>/',change_item,name='change_item'), 
    path('change-item-<int:item_id>/change-subitem-<int:subitem_id>/',change_subitem,name='change_subitem'),
    path('change-item-<int:item_id>/create-subitem/',create_subitem,name='create_subitem'),
    path('profile/',profile,name='profile'),
    path('publication-<int:item_id>/',publication,name='publication')
]

src/newssite/newssite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from newsapp import views
from accs.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('news/',include('newsapp.urls')),
    path('accs/',include('accs.urls'))
     
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/newssite/accs/models.py
from django.db import models

# Create your models here.

src/newssite/newsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey,GenericRelation

class Tag(models.Model):
    name=models.CharField(max_length=50,unique=True)
    def __str__(self):
        return self.name

class Like(models.Model):
    user=models.ForeignKey(User,related_name='likes',on_delete=models.CASCADE)
    content_type=models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id=models.PositiveBigIntegerField()
    content_object=GenericForeignKey('content_type','object_id')

class Item(models.Model):
    title=models.CharField(max_length=100)
    memo =models.TextField()
    image=models.ImageField(upload_to='newsapp/images',null=True,blank=True)
    date=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    published=models.BooleanField(default=False,null=False,blank=False)
    likes=GenericRelation(Like)
    tags=models.ManyToManyField(Tag)
    class Meta:
        permissions=[('can_read_item','Can read item')]
    @property
    def total_likes(self):
        return self.likes.count()
    def __str__(self) :
        return self.title +'%with id%'+str(self.id)

    
class SubItem(models.Model):
    title=models.CharField(max_length=100)
    memo =models.TextField()
    image=models.ImageField(upload_to='newsapp/images',null=True,blank=True)
    video=models.FileField(upload_to='newsapp/videos',null=True,blank=True)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    def __str__(self) :
          return self.title +'%with parrent id%'+str(self.item) 


class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.PROTECT)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    class Meta:
        unique_together=('user','item',)

src/newssite/accs/forms.py
from newsapp.models import * 
from django.forms import ModelForm

class CreateItemForm(ModelForm):
    class Meta:
        model=Item
        fields=['title','memo','image']

class ChangeItemForm(ModelForm):
    class Meta:
        model=Item
        fields=['title','memo']

class Create_SubItem_Form(ModelForm):
    class Meta:
        model=SubItem
        fields=['title','memo','image','video']
        
class Change_SubItem_Form(ModelForm):
    class Meta:
        model=SubItem
        fields=['title','memo']

src/newssite/accs/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from accs.forms import *
def signup(request):
    if request.method=='GET':
      return render(request,'accs/signup.html',{'form':UserCreationForm()})
    else:
       if request.POST['password1']==request.POST['password2']:
          print(str(request.POST['password1']),str(request.POST['password2']))
          try:
             user=User.objects.create_user(username=request.POST['username'],password=request.POST['password1'])
             user.save()
             login(request,user)
             return redirect('newsapp:home')
          except IntegrityError:
             return render(request,'accs/signup.html',{'form':UserCreationForm(),'error':'this is error'})
       else:
           return render(request,'accs/signup.html',{'form':UserCreationForm(),'error':'password did not match '})  
       

@login_required
def signout(request):
   if request.method=='POST':
      logout(request)
      return redirect('newsapp:home')


def signin(request):
    if request.method=='GET':
      return render(request,'accs/signin.html',{'form':AuthenticationForm()})
    else:
      u=authenticate(request,username=request.POST["username"],password=request.POST["password"])
    
      if u is None:
          return render(request,'accs/signin.html',{'form':AuthenticationForm(),'error':'user is not exists'})
      else:
        login(request,u)
        return redirect('newsapp:home')


@login_required
def createitem(request):
   if request.method=='GET':
      return render(request,'accs/createitem.html',{'form':CreateItemForm()})
   else: 
      try:
         form=CreateItemForm(request.POST, request.FILES)
         newitem=form.save(commit=False)
         newitem.author=request.user
         newitem.save()
         return redirect('newsapp:home')
      except ValueError:
          return render(request,'accs/createitem.html',{'form':CreateItemForm(),'error':'неккоректные данные'})
      
@login_required
def viewitem(request,item_id):
   bigitem=get_object_or_404(Item,pk=item_id,author=request.user) # над этим стоит задуматься 
   smallitems=SubItem.objects.all().filter(item=item_id)
   return render(request,'accs/viewitem.html',{'bigitem':bigitem,'smallitems':smallitems})

@login_required
def change_item(request,item_id):
   bigitem=get_object_or_404(Item,pk=item_id,author=request.user)
   if request.method=='GET':
      form=CreateItemForm(instance=bigitem)
      tags=bigitem.tags.all()
      return render(request,'accs/change_item.html',{'bigitem':bigitem,'tags':tags})
   else: 
      form=CreateItemForm(request.POST,request.FILES,instance=bigitem)
      bigitem=form.save(commit=True)
      tags=str(request.POST['tags']) # если пользователь дурачок, то он не поставит пробелы и надо бы решить эту проблему но можно и не решать пусть другие решают 
      tags=tags.split()
      bigitem.tags.clear()
      for i in tags: 
         try: 
            t=Tag.objects.create(name=i)

         except: 
            t=Tag.objects.get(name=i)
         finally:
            bigitem.tags.add(t)
      bigitem.save()
      return redirect('newsapp:home')
   

@login_required
def create_subitem(request,item_id):
   if request.method=='GET':
        return render(request,'accs/create_subitem.html',{'form':Create_SubItem_Form()})
   else: 
      try:
         form=Create_SubItem_Form(request.POST, request.FILES)
         newitem=form.save(commit=False)
         newitem.item=Item.objects.get(id=item_id)
         newitem.save()
         return redirect('accs:viewitem',item_id=item_id)
      except ValueError:
          return render(request,'accs/create_subitem.html',{'form':Create_SubItem_Form(),'error':'неккоректные данные'})


@login_required  
def change_subitem(request,item_id,subitem_id):
   bigitem=get_object_or_404(Item,pk=item_id,author=request.user)
   subitem=get_object_or_404(SubItem,pk=subitem_id,item=bigitem)
   if request.method=='GET':
      form=Create_SubItem_Form(instance=subitem)
      return render(request,'accs/change_subitem.html',{'subitem':subitem})
   else: 
      form=Create_SubItem_Form(request.POST,request.FILES,instance=subitem)
      form.save(commit=True)
      return redirect('accs:viewitem',item_id=item_id)


@login_required
def profile(request):
   publicnews=Item.objects.filter(author=request.user,published=True)
   shadownews=Item.objects.filter(author=request.user,published=False)
   return render(request,'accs/profile.html',{'publicnews':publicnews,'shadownews':shadownews})

@login_required
def publication(request,item_id):
   item=get_object_or_404(Item,pk=item_id,author=request.user)
   if item.published: 
      item.published=False
   else: 
      item.published=True
   item.save()
   return redirect('accs:profile')

src/newssite/accs/templates/accs/change_item.html
{% extends 'coreapp/base.html' %}
{% load static %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <p>
    <label for="id_title">Title:</label>
    <input type="text" name="title" maxlength="100" required id="id_title" value="{{ bigitem.title }}">
    
    
  </p>

  
  <p>
    <label for="id_memo">Memo:</label>
    <textarea name="memo" cols="40" rows="10" required id="id_memo">
      {{ bigitem.memo }}
</textarea>

  </p>

  <p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" accept="image/*" id="id_image" >
  </p>
  <label for="id_tags">Tags:</label>
  <input name="tags" required id="id_tags" type="text" value="{% for i in tags  %} {{ i.name }} {% endfor %}">

  <button  type="submit" class="btn btn-primary">Сохранить</button>
</form>

{% if bigitem.published %}
<form action="" method="post"> <button  class="btn btn-danger" type="submit">Скрыть </button> </form>
{% else %}
<form action="" method="post">  </form>
{% endif %}
<small>{{ error }}</small>
{% endblock %}

src/newssite/accs/templates/accs/change_subitem.html
{% extends 'coreapp/base.html' %}
{% load static %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <p>
    <label for="id_title">Title:</label>
    <input type="text" name="title" maxlength="100" required id="id_title" value="{{ subitem.title }}">
    
    
  </p>

  
  <p>
    <label for="id_memo">Memo:</label>
    <textarea name="memo" cols="40" rows="10" required id="id_memo">
      {{ subitem.memo }}
</textarea>

  </p>

  <p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" accept="image/*" id="id_image" >
  </p>

  <p>
    <label for="id_video">Video:</label>
    <input type="file" name="video" accept="video/*" id="id_video" >
  </p>
  <button  type="submit" class="btn btn-primary">Сохранить</button>
</form>

{% if bigitem.published %}
<form action="" method="post"> <button  class="btn btn-danger" type="submit">Скрыть </button> </form>
{% else %}
<form action="" method="post">  </form>
{% endif %}
<small>{{ error }}</small>
{% endblock %}

src/newssite/accs/templates/accs/create_subitem.html
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="создать">
</form>
<small>{{ error }}</small>

src/newssite/accs/templates/accs/createitem.html
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="сделать статью"> 
</form>
<small>{{ error }}</small>

src/newssite/accs/templates/accs/profile.html
{% extends 'coreapp/base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <h2 class="mt-3">Мой профиль</h2>
<h2 class="mt-3">Мои статьи</h2>
<h3 class="mt-3">Опубликованные</h3>
{% for i in publicnews %}

  <div class="card mt-2 bg-secondary ">
  
    <div class="card-body">
  
    <a class="nav-link" href="{% url 'accs:viewitem' i.id %}"><h4>{{ i.title }}</h4></a>
  
    <a href="{% url 'accs:publication' i.id %}" class="btn btn-outline-info">скрыть </a>
    </div>
  </div>
{% endfor %}
<h3 class="mt-3">Скрытые</h3>
{% for j in shadownews %}

<div class="card mt-2 bg-secondary ">
  
  <div class="card-body">

  <a class="nav-link" href="{% url 'accs:viewitem' j.id %}"><h4>{{ j.title }}</h4></a>

  <a href="{% url 'accs:publication' j.id %}" class="btn btn-outline-info">опубликовать </a>
  </div>
</div>
{% endfor %}
<br>
<a class="btn btn-outline-success" href="{% url 'accs:createitem'  %}" role="button">Добавить статью</a>
</div>

{% endblock %}

src/newssite/accs/templates/accs/publication.html
{% comment %} {% if item.published %}
{%item.published=0%}
{% else %}
{%item.published=1%}
{% endif %} {% endcomment %}

src/newssite/accs/templates/accs/signin.html
{% extends 'coreapp/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">

  <h2>Форма входа</h2>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">войти</button>
</form>
<h6> {{ error }}</h6>
</div>
{% endblock %}

src/newssite/accs/templates/accs/signup.html
{% extends 'coreapp/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
  <h2>Форма регистрации</h2>
<form action="" method="post">
  {% csrf_token %}

  <p>
    <label for="id_username">Username:</label>
    <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username">
    
 
    
    
  </p>

  
  <p>
    <label for="id_password1">Password:</label>
    <input type="password" name="password1" autocomplete="new-password" required id="id_password1">
    
  
    
    
  </p>

  
  <p>
    <label for="id_password2">Password confirmation:</label>
    <input type="password" name="password2" autocomplete="new-password" required id="id_password2">
    
   
    
    
      
    
  </p>
  <input type="submit" value="Зарегестрироваться">
</form>
<h6> {{ error }}</h6>
</div>
{% endblock %}

src/newssite/accs/templates/accs/viewitem.html
{% extends 'coreapp/base.html' %}
{% load static %}
{% block content %}
<div class="container">
<div class="card mt-2 bg-secondary">

  <div class="card-body">

   

   <a href="{% url 'accs:change_item' bigitem.id %}"><b><h2>{{ bigitem.title }}</h2></b></a>
   {{ bigitem.memo}}
  </div>
</div>

{% for i in smallitems %}
<div class="card mt-5 bg-secondary ">

  <div class="card-body">
     <a href="{% url 'accs:change_subitem' bigitem.id i.id %}"><b><h2>{{ i.title }}</h2></b></a>
     {{ i.memo}}
  </div>
</div>



{% endfor %}
<br>

<div class="card mt-2 bg-secondary "> 
  <div class="card-body">
   {% if bigitem.published %}
     <a href="{% url 'accs:publication' bigitem.id %}" class="btn btn-info">скрыть </a>
   {% else %}
     <a href="{% url 'accs:publication' bigitem.id %}" class="btn btn-info">опубликовать </a>
   {% endif %}
 <a href="{% url 'accs:create_subitem' bigitem.id %}" class="btn btn-success">создать блок</a>
  </div>
</div>

</div>
{% endblock %}