src/newssite/accs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from accs.views import *
app_name='accs'
urlpatterns = [
    path('sign-up/',signup,name='signup'),
    path('sign-in/',signin,name='signin'),
    path('sign-out/',signout,name='signout'),
    path('create-item/',createitem,name='createitem'),
    path('view-item-<int:item_id>/',viewitem,name='viewitem'), 
    path('change-item-<int:item_id>/',change_item,name='change_item'), 
    path('change-item-<int:item_id>/change-subitem-<int:subitem_id>/',change_subitem,name='change_subitem'),
    path('change-item-<int:item_id>/create-subitem/',create_subitem,name='create_subitem'),
    path('profile/',profile,name='profile'),
    path('publication-<int:item_id>/',publication,name='publication')
]

src/newssite/newsapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from newsapp import views


app_name='newsapp'
urlpatterns = [
path('',views.home,name='home'),
  path('item-<int:item_id>/',views.item,name='item'),
  path('open-item-<int:item_id>-in-author-mode/',views.open_item_in_author_mode,name='open_item_in_author_mode',)
     
     
]

src/newssite/newssite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from newsapp import views
from accs.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('news/',include('newsapp.urls')),
    path('accs/',include('accs.urls'))
     
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/newssite/newsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey,GenericRelation

class Tag(models.Model):
    name=models.CharField(max_length=50,unique=True)
    def __str__(self):
        return self.name

class Like(models.Model):
    user=models.ForeignKey(User,related_name='likes',on_delete=models.CASCADE)
    content_type=models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id=models.PositiveBigIntegerField()
    content_object=GenericForeignKey('content_type','object_id')

class Item(models.Model):
    title=models.CharField(max_length=100)
    memo =models.TextField()
    image=models.ImageField(upload_to='newsapp/images',null=True,blank=True)
    date=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    published=models.BooleanField(default=False,null=False,blank=False)
    likes=GenericRelation(Like)
    tags=models.ManyToManyField(Tag)
    class Meta:
        permissions=[('can_read_item','Can read item')]
    @property
    def total_likes(self):
        return self.likes.count()
    def __str__(self) :
        return self.title +'%with id%'+str(self.id)

    
class SubItem(models.Model):
    title=models.CharField(max_length=100)
    memo =models.TextField()
    image=models.ImageField(upload_to='newsapp/images',null=True,blank=True)
    video=models.FileField(upload_to='newsapp/videos',null=True,blank=True)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    def __str__(self) :
          return self.title +'%with parrent id%'+str(self.item) 


class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.PROTECT)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    class Meta:
        unique_together=('user','item',)

src/newssite/newsapp/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse
from django.contrib.auth.decorators import login_required
from newsapp import models
def home(request):
    user_filter_status=request.session.get('user_filter_status','down')
    
    data=models.Item.objects.all()
    if request.GET.get('filter_by')=='up':
           request.session['user_filter_status']='up'
           user_filter_status= request.session['user_filter_status']
           data=models.Item.objects.all().order_by('date')
        
    elif request.GET.get('filter_by')=='down':
            request.session['user_filter_status']='down'
            user_filter_status= request.session['user_filter_status']
            data=models.Item.objects.all().order_by('-date')
           
    return render(request,'newsapp/home.html',{'data':data,'user_filter_status':user_filter_status})


# на этом примере будут permissions 
def item(request,item_id): 
    if request.user.has_perm('newsapp.can_read_item'):
        parrentobj=get_object_or_404(models.Item,pk=item_id)
        childobject=models.SubItem.objects.all().filter(item=item_id)
        try:
            r=models.Review.objects.create(item=parrentobj,user=request.user)
            r.save()
        except:
            pass
        countofviews=models.Review.objects.filter(item=parrentobj).all().count()
        tags=parrentobj.tags.all()
        return render(request,'newsapp/item.html',{'parrentobj':parrentobj,'childobject':childobject,'tags':tags,'countofviews':countofviews})
    else:
         return HttpResponse('<h2>Permissions denied </h2>')


@login_required
def open_item_in_author_mode(request,item_id):
    item=get_object_or_404(models.Item,pk=item_id,author=request.user)
    return redirect('accs:viewitem',item_id=item_id)
# Create your views here.

src/newssite/newsapp/templates/newsapp/home.html
{% extends 'coreapp/base.html' %}

  {% block content %}
<div class="container mt-5">

<h2>Рекомендуемые статьи</h2>
<form action="" method="get">
<select name="filter_by" id="">
  <option value="up" {% if user_filter_status == 'up' %} selected {% endif %}>по возрастанию</option>
  <option value="down" {% if user_filter_status == 'down' %} selected {% endif %} >по убыванию</option>
  <input type="submit" value="отфильтровать">
</select>
</form>
<br>
{% autoescape off %}
  {% for i in data %}
  {% if i.published %}
  <div class="card mb-3">
    {% if i.image %}
    <img src="{{ i.image.url }}" class="card-img-top" alt="картинка" >
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">{{ i.title }}</h5>
      <p class="card-text">{{ i.memo }}</p>
      <a href="{% url 'newsapp:item' i.id %}" class="btn btn-info">читать</a>
    </div>
  </div>
  {% endif %}
  
  


  {% endfor %}
</div>
{% endautoescape %}
  {% endblock %}

src/newssite/newsapp/templates/newsapp/item.html
{% extends 'coreapp/base.html' %}

  {% block content %}
  <div class="container mt-3">
    <h2>
      {{ parrentobj.title }}
    </h2>
<small class="text-muted">автор: {{ parrentobj.author }}</small>
<br>
<small class="text-muted"> просмотры: {{ countofviews }}</small>
{%  for j in tags %}
<small class="text-muted">{{ j.name }}</small>
{% endfor %}
{% for i in childobject %}
<h3>
  {{ i.title }}
</h3>
<p>{{ i.memo }}</p>

{% if i.image %}
<img src="{{ i.image.url }}" alt="картинка">
{% endif %}
{% endfor %} 

<br> 



{% if parrentobj.author == user %}
<a href="{% url 'newsapp:open_item_in_author_mode' parrentobj.id %}"><b>Раскрыть</b></a>
{% endif %}

</div>

  {% endblock %}